// demos/02-vue-spa/src/components/RestaurantTable.vue
<script setup lang="ts">
import type { Restaurant } from '../types'
import RestaurantRow from './RestaurantRow.vue'

// Define props
defineProps<{
  restaurants: Restaurant[]
}>()
</script>

<template>
  <article>
    <h2>Lunch Locations</h2>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Cuisine</th>
          <th>Distance</th>
          <th>Diet Options</th>
          <th>Card Payment</th>
          <th>Address</th>
        </tr>
      </thead>
      <tbody>
        <RestaurantRow 
          v-for="place in restaurants" 
          :key="place.id" 
          :restaurant="place" 
        />
      </tbody>
    </table>
  </article>
</template>

// demos/03-ssr-react/src/components/RestaurantTable.tsx
import { RestaurantWithDistance } from "../utils/types";
import RestaurantRow from "./RestaurantRow";

interface RestaurantTableProps {
    restaurants: RestaurantWithDistance[];
}

const RestaurantTable = ({ restaurants }: RestaurantTableProps) => {
    return (
        <article>
            <h2>Lunch Locations</h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Cuisine</th>
                        <th>Distance</th>
                        <th>Diet Options</th>
                        <th>Card Payment</th>
                        <th>Address</th>
                    </tr>
                </thead>
                <tbody>
                    {restaurants.map(restaurant => (
                        <RestaurantRow key={restaurant.id} restaurant={restaurant} />
                    ))}
                </tbody>
            </table>
        </article>
    );
};

export default RestaurantTable;
