// demos/03-ssr-react/src/app.tsx
import { useState } from "react";
import { OfficeLocationId, officeLocations } from "./utils/office-locations";
import { RestaurantWithDistance } from "./utils/types";
import { fetchLunchPlaces } from "./utils/api";
import LocationSelector from "./components/LocationSelector";
import InitialMessage from "./components/InitialMessage";
import LoadingIndicator from "./components/LoadingIndicator";
import RestaurantTable from "./components/RestaurantTable";
import NoResults from "./components/NoResults";

export const App = () => {
    const [selectedLocationId, setSelectedLocationId] = useState<OfficeLocationId | null>(null);
    const [restaurants, setRestaurants] = useState<RestaurantWithDistance[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [showInitialMessage, setShowInitialMessage] = useState(true);

    // Sort places by distance
    const sortPlacesByDistance = (places: RestaurantWithDistance[]): RestaurantWithDistance[] => {
        return [...places].sort((a, b) => a.distance - b.distance);
    };

    // Handle location change
    const updateRestaurants = async (locationId: OfficeLocationId) => {
        setSelectedLocationId(locationId);

        setShowInitialMessage(false);
        setIsLoading(true);

        try {
            const selectedOffice = officeLocations[locationId as OfficeLocationId   ];

            if (!selectedOffice) {
                throw new Error("Selected office not found");
            }

            const places = await fetchLunchPlaces(selectedOffice);
            setRestaurants(sortPlacesByDistance(places));
        } catch (error) {
            console.error("Error fetching lunch places:", error);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <main className="container">
            <LocationSelector
                selectedLocationId={selectedLocationId}
                onLocationIdChange={updateRestaurants}
            />

            <section>
                <h2>Lunch places near you</h2>
                {showInitialMessage && <InitialMessage />}
                {isLoading && <LoadingIndicator />}
                {!isLoading && !showInitialMessage && restaurants.length === 0 && <NoResults />}
                {!isLoading && !showInitialMessage && restaurants.length > 0 && (
                    <RestaurantTable restaurants={restaurants} />
                )}
            </section>
        </main>
    );
};

// demos/02-vue-spa/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { fetchLunchPlaces } from './api'
import type { Restaurant } from './types'
import { officeLocations } from './office-locations'
import LocationSelector from './components/LocationSelector.vue'
import InitialMessage from './components/InitialMessage.vue'
import LoadingIndicator from './components/LoadingIndicator.vue'
import RestaurantTable from './components/RestaurantTable.vue'

// Reactive state
const selectedLocation = ref('')
const isLoading = ref(false)
const lunchPlaces = ref<Restaurant[]>([])
const showInitialMessage = ref(true)

// Sort function to sort places by distance
function sortPlacesByDistance(places: Restaurant[]): Restaurant[] {
  return [...places].sort((a, b) => a.distance - b.distance)
}

// Handle location change
async function handleLocationChange() {
  if (!selectedLocation.value) return
  
  showInitialMessage.value = false
  isLoading.value = true
  
  try {
    // Find the selected location object
    const selectedOffice = officeLocations.find(loc => loc.id === selectedLocation.value)
    
    if (!selectedOffice) {
      throw new Error("Selected office not found")
    }
    
    const places = await fetchLunchPlaces(selectedOffice)
    lunchPlaces.value = sortPlacesByDistance(places)
  } catch (error) {
    console.error("Error fetching lunch places:", error)
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <main class="container">
    <LocationSelector 
      v-model:selectedLocation="selectedLocation"
      @locationChange="handleLocationChange"
    />

    <section>
      <h2>Lunch places near you</h2>
      
      <!-- Initial message -->
      <InitialMessage v-if="showInitialMessage" />
      
      <!-- Loading state -->
      <LoadingIndicator v-else-if="isLoading" />
      
      <!-- Results table -->
      <RestaurantTable 
        v-else 
        :restaurants="lunchPlaces"
      />
    </section>
  </main>
</template>
